homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'
urlpatterns = [
    path('', views.index, name='homepage-index'),
    path('search/', views.SerarchResultView, name='search'),
    ]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import settings
from django.conf.urls.static import static
from user import views as user_views

urlpatterns = [
    url('admin/', admin.site.urls, name='admin'),
    url('', include('homepage.urls')),
    url('product/', include('product.urls')),
    url('shop/', include('shop.urls')),
    url('user/', include('user.urls')),
    url('order/', include('order.urls')),
    url('basket/', include('user_basket.urls')),

    path('login/', user_views.Login, name='login'),
    path('logout/', user_views.LogOut, name='logout'),
    path('register/', user_views.UserSignUp, name='register'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


























order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns = [
    path('list/', views.OrderListView, name='list'),
    path('orderNO/Detail/', views.OrderDetailView, name='detail'),
    path('process-order/', views.BasketCheckOutProcess, name='process-order'),
    path('process/<product_id>/<shop_id>/', views.OrderProcessing, name='process'),
    path('order-detail/', views.OrderDetailView, name='order-detail'),
    path('place-order/', views.CheckoutBasketView, name='place-order'),
    path('checkout/<product_id>/<shop_id>/', views.CheckOutView, name='checkout')
]

product/urls.py
from django.urls import path
from django.conf.urls import url
from product import views

app_name = 'product'
urlpatterns = [
    # /products/
    path('', views.product_list, name='product-list'),

    # /product/<pk>/ # to be done later
    path('<pk>/', views.productView, name='productView'),
]

shop/urls.py
from django.urls import path
from . import views


app_name = 'Shop'
urlpatterns = [

    path('', views.ShopListView, name='shop-list'),

    path('sd/<pk>/', views.ShopDetailView, name='shop-detail'),

    path('sc/<pk>/context/', views.ShopDetailContextView, name='shop-context'),

    path('sr/<pk>/add_review/', views.ShopAddReview, name="add-review"),

    path('AddNewShop/', views.AddNewShop.as_view(), name="add-shop"),

    # path('something/', views.AddNewShop.as_view(), name="something")
]


user/urls.py
from django.urls import path
from . import views as user_views
from django.contrib.auth import views as auth_views


app_name = 'user'
urlpatterns = [
    path('profile/', user_views.UserProfileView, name="profile"),
]

user_basket/urls.py
from django.urls import path
from user_basket import views as basket_views

app_name = 'basket'
urlpatterns = [
    path('', basket_views.ListView, name='list'),
    path('add-item/<product_id>/<shop_id>/', basket_views.AddToBasket, name='add-item'),
    path('rm-item/<basket_product_id>/', basket_views.RemoveFromBasket, name='remove-item'),
    path('update-item/<int:basket_product_id>/', basket_views.UpdateQuantity, name='update'),
]

homepage/models.py
from django.db import models



homepage/views.py
from django.shortcuts import render, HttpResponse, reverse, redirect
from product import models as product_models
from shop import models as shop_models
from order import models as order_models


def index(request):
    context = {
        'trending_products': [product for product in order_models.product_data.objects.all()[:50]],
        'nearby_shops': [shop for shop in shop_models.Shop.objects.all()[:20]],
        'nearby_products': [product for product in order_models.product_data.objects.all()[200:250]],
        'history_product': [product for product in order_models.product_data.objects.all()[250:300]],
    }
    return render(request, 'homepage/homepage.html', context)


def SerarchResultView(request):
    if request.method == "POST":
        searched_text = request.POST['search_text']
        if searched_text:
            searched_products = product_models.product_data.objects.filter(name__icontains=searched_text)[:50]
            if searched_products:
                context = {
                    'searched_text': searched_text,
                    'products': searched_products,
                }
            else:
                context = {
                    'searched_text': searched_text,
                    'error_message': f'No items has been found for {searched_text}!'
                }
                return render(request, 'product/product_list.html', context)

        else:
            return redirect('homepage:homepage-index')
    else:
        return redirect('homepage:homepage-index')

    return render(request, 'product/product_list.html', context)

homepage/templates/homepage/base.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no,
    initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

            <title>MyStore</title>

    <link rel="icon" href="{% static 'homepage/Pics/logo.png' %}" type="image/gif" sizes="16x16">
    <link rel="stylesheet" href="{% static 'homepage/CSS/Style4index.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/CSS/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/CSS/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/CSS/jquery-ui.css' %}">

</head>

    <body style="background-color: yellowgreen">
        <header>
          {% include 'homepage/navbar.html' %}
        </header>

        {% block body %}
        {% endblock %}

        {% include 'homepage/sign-in_up-pop-up.html' %}
        {% include 'homepage/category.html' %}
        {% include 'homepage/footer.html' %}

        <!-- Scripts -->
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="{% static 'homepage/JS/bootstrap.min.js' %}"></script>
        <script src="{% static 'homepage/JS/jquery.js' %}"></script>
        <script src="{% static 'homepage/JS/jquery-ui.js' %}"></script>
        <script src="{% static 'homepage/JS/fontawesome.min.js' %}"></script>
        <script>
        {% if not request.user.is_authenticated %}
        document.getElementById('BUTTON').addEventListener('click',function(){
            document.querySelector('.BG_MODAL').style.display='flex';
            });
        $(document).ready(function(){
            $("#SIGNUP").click(function(){
                $("#SIGNINPAGE").toggle();
                $("#SIGNUPPAGE").toggle();
            });
         });
        $(document).ready(function(){
            $("#SIGNUP2").click(function(){
                $("#SIGNINPAGE").toggle();
                $("#SIGNUPPAGE").toggle();
            });
        });
        document.querySelector('.CLOSE').addEventListener('click',function(){
            document.querySelector('.BG_MODAL').style.display='none';
            });
        {% endif %}

        //Category Script
        document.getElementById('Category_PAGEButton').addEventListener('click',function(){
            document.querySelector('.Category_PAGE').style.display='flex';
            });
        document.querySelector('.CLOSECategory_PAGE').addEventListener('click',function(){
            document.querySelector('.Category_PAGE').style.display='none';
            });

        var acc = document.getElementsByClassName("accordion");
            var i;

            for (i = 0; i < acc.length; i++) {
                acc[i].addEventListener("click", function() {
                this.classList.toggle("active");
                var panel = this.nextElementSibling;
                if (panel.style.maxHeight){
                   panel.style.maxHeight = null;
                } else {
                        panel.style.maxHeight = panel.scrollHeight + "px";
                }
              });
            }
      </script>
    {% block scripts %}
    {% endblock %}
	</body>
  </html>

homepage/templates/homepage/category.html
<!--Category-->

<div class="Category_PAGE">
  <div class="Category_PAGE_Inside" >
    <div class="CLOSECategory_PAGE" style="color: white;">+</div><br><br>
    <button class="accordion" >Cloth </button>
    <div class="panel">
          <div class="List">
                <li><a href="#">Product list</a></li>
                <li><a href="#">Reviews</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Product list</a></li>
                <li><a href="#">Reviews</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Product list</a></li>
                <li><a href="#">Reviews</a></li>
                <li><a href="#">About</a></li>

          </div>
          <div class="List">
                <li><a href="#">Product list</a></li>
                <li><a href="#">Reviews</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Product list</a></li>
                <li><a href="#">Reviews</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Product list</a></li>
                <li><a href="#">Reviews</a></li>
                <li><a href="#">About</a></li>
          </div>

    </div>

    <button class="accordion"> Grocery</button>
    <div class="panel">
            <div class="List">
                <li><a href="#">Product list</a></li>
                <li><a href="#">Reviews</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Product list</a></li>
                <li><a href="#">Reviews</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Product list</a></li>
                <li><a href="#">Reviews</a></li>
                <li><a href="#">About</a></li>

            </div>
            <div class="List">
                <li><a href="#">Product list</a></li>
                <li><a href="#">Reviews</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Product list</a></li>
                <li><a href="#">Reviews</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Product list</a></li>
                <li><a href="#">Reviews</a></li>
                <li><a href="#">About</a></li>
            </div>

      </div>
      <button class="accordion" >Stationary </button>
    <div class="panel">
          <div class="List">
                <li><a href="#">Product list</a></li>
                <li><a href="#">Reviews</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Product list</a></li>
                <li><a href="#">Reviews</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Product list</a></li>
                <li><a href="#">Reviews</a></li>
                <li><a href="#">About</a></li>

          </div>
          <div class="List">
                <li><a href="#">Product list</a></li>
                <li><a href="#">Reviews</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Product list</a></li>
                <li><a href="#">Reviews</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Product list</a></li>
                <li><a href="#">Reviews</a></li>
                <li><a href="#">About</a></li>
          </div>

    </div>

    <button class="accordion" >Books</button>
    <div class="panel">
          <div class="List">
                <li><a href="#">Product list</a></li>
                <li><a href="#">Reviews</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Product list</a></li>
                <li><a href="#">Reviews</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Product list</a></li>
                <li><a href="#">Reviews</a></li>
                <li><a href="#">About</a></li>

          </div>
          <div class="List">
                <li><a href="#">Product list</a></li>
                <li><a href="#">Reviews</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Product list</a></li>
                <li><a href="#">Reviews</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Product list</a></li>
                <li><a href="#">Reviews</a></li>
                <li><a href="#">About</a></li>
          </div>

    </div>
  </div>
</div>

homepage/templates/homepage/footer.html
<!-- 2nd last footer -->
<div class="SecondndLastFooterOfWebsite">
        <div class="List4SecondndLastFooter">
                <li style="color:white;"><a><h8><u>About us</u></h8></a></li>
                <li><a  href="#" style="color:white;"> CSE</a></li>
                <li><a href="#" style="color:white;"> CSE</a></li>
                <li><a href="#" style="color:white;"> CSE</a></li>
        </div>
        <div class="List4SecondndLastFooter">
                <li style="color:white;"><a><h8><u>Contact us</u></h8></a></li>
                <li><a  href="#" style="color:white;"> CSE</a></li>
                <li><a href="#" style="color:white;"> CSE</a></li>
                <li><a href="#" style="color:white;"> CSE</a></li>
        </div>
        <div class="List4SecondndLastFooter">
                <li style="color:white;"><a><h8><u>Acount</u></h8></a></li>
                <li><a  href="#" style="color:white;"> CSE</a></li>
                <li><a href="#" style="color:white;"> CSE</a></li>
                <li><a href="#" style="color:white;"> CSE</a></li>
        </div>
        <div class="List4SecondndLastFooter">
                <li style="color:white;"><a><h8><u>Help</u></h8></a></li>
                <li><a  href="#" style="color:white;"> CSE</a></li>
                <li><a href="#" style="color:white;"> CSE</a></li>
                <li><a href="#" style="color:white;"> CSE</a></li>
        </div>
</div>
<!--last footer  -->
<nav class="navbar bottom navbar-dark bg-dark">
       <h5 style="color:white;">@Copyright</h5>
</nav>

homepage/templates/homepage/navbar-profile.html
<li class="nav-item dropdown">

    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
       role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            (-.-)
    </a>

    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="{% url 'user:profile' %}">Profile</a>
        <a class="dropdown-item" href="{% url 'order:list' %}">Orders</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
    </div>
</li>

homepage/templates/homepage/navbar.html
		    <nav class="navbar top navbar-light">
			    <a class="navbar-brand" href="{% url 'homepage:homepage-index' %}" style="color:black;"><h3>MyStore</h3></a>
                <div class="input-group md-form form-sm form-2 pl-0 mr-auto" style="width:600px;">

                    <form class="form-inline my-5 my-lg-0" action="{% url 'homepage:search' %}" method="post">
                        {% csrf_token %}

                        <input class="form-control mr-sm-2" id="search" type="search" placeholder="Search"
                               name="search_text" value="{{ searched_text }}" aria-label="Search" style="width: 400px;">

                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form>

                </div>

            <a class="mr-auto"><i class="fa fa-android fa-3x "></i></a>
            <a class="mr-auto"><i class="fa fa-phone fa-2x"></i></a>
                {% if not request.user.is_authenticated %}
                      <button class="btn btn-outline-secondary" type="button" id="BUTTON">Login</button>
                {% else %}
                    <li class="dropdown dropleft">
                        <a class=" dropdown-toggle navbar-brand" data-toggle="dropdown" href="#" style="color:black;">Profile</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'user:profile' %}">Account</a>
                            <a class="dropdown-item" href="{% url 'order:list' %}">Orders</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
                        </div>
                    </li>
                {% endif %}
          </nav>
          <nav class="navbar top navbar-light">
            <a href="#" class="mr-auto" style="color:black;"><i class="fa fa-map-marker"> Deliver to <br>Default Address</i></a>
            <a id="Category_PAGEButton" class="navbar-brand mr-auto" style="color:black;"><h5>Categories</h5></a>
            <a class="navbar-brand mr-auto" href="{% url 'Shop:shop-list' %}" style="color:black;"><h5>Shop</h5></a>
            <a class="navbar-brand mr-auto" href="#" style="color:black;"><h5>Offer</h5></a>
            <a class="navbar-brand mr-auto" href="#" style="color:black;"><h5>Instant Offer</h5></a>

            <a href="{% url 'basket:list' %}"><i class="fa fa-shopping-cart fa-2x"></i></a>
		  </nav>

homepage/templates/homepage/product-block.html
{% load static %}
    <a href="{% url 'product:productView' product.pk %}" style="text-decoration: none;">
        <b style="color: black;">{{ product.name }}</b><br>
        <img class="ProductImageNew" src="{{ product.image_link.url }}" alt=""><br>
    </a>
    <b class="PriceDetailsInTemplate"><small><del>MRP Rs. {{ product.price }}</del></small><br>Price Rs. {{ product.price }}</b><br>
    {% if product.pk > 200 %}
        <a href="{% url 'order:process' product.pk 2 %}">
            <img src="{% static 'homepage/Pics/checkout.png' %}" class="BuyNowButtonStyle" alt="Buy">
        </a>
        <a href="{% url 'basket:add-item' product.pk 2%}"><i class="fas fa-cart-plus AddToCartButtonStyle"></i></a>

    {% else %}

        <a href="{% url 'order:process' product.pk 3 %}">
            <img src="{% static 'homepage/Pics/checkout.png' %}" class="BuyNowButtonStyle" alt="Buy">
        </a>
        <a href="{% url 'basket:add-item' product.pk 3%}"><i class="fas fa-cart-plus AddToCartButtonStyle"></i></a>
    {% endif %}

homepage/templates/homepage/search-result.html
{% extends 'homepage/base.html' %}

{% block body %}
    <div class="container">
        
    </div>
{% endblock %}

homepage/templates/homepage/shop-block.html
{% load static %}
<div class="Ashop mySlides4">
    <img class="AshopImage" src="{{ shop.Shop_icon.url }}"><br>
    <a href="{% url 'Shop:shop-detail' shop.pk %}"><b>{{ shop.title }}</b></a>
</div>


homepage/templates/homepage/sign-in_up-pop-up.html
      <!--Pop up page  -->
	      <div class="BG_MODAL">
			  <div class="MODAL_CONTENT">
                  <div class="CLOSE">+</div>
                  <form id="SIGNINPAGE" action="{% url 'login' %}" method="post">
                      {% csrf_token %}
                      <fieldset>
                          <input type="text" id="lphone" name="phone" placeholder="Mobile no">
                          <input type="password" id="lpass" name="password" placeholder="Password">
                          <input type="hidden" name="current_url" value="{{ request.get_full_path }}">

                      </fieldset>
                        <button type="submit" class="button">Login</button>
                        <a href="#">Forgot Password?</a><br><br>
                    <button  type="button" id="SIGNUP" class="btn">New to Web? Sign up</button>
                  </form>

                  <form id="SIGNUPPAGE" action="{% url 'register' %}" method="post">
                      {% csrf_token %}
                      <input type="text" id="sphone" name="phone" placeholder="Mobile no">
                      <input type="text" id="semail" name="email" placeholder="email">
                      <input type="password" id="spass" name="password" placeholder="Password">
                      <input type="password" id="scpass" placeholder="ReEnter Password">
                      <button type="button" id="SIGNUP2" class="btn btn-outline-light">Existing User? Log in &nbsp;<br></button>
                      <button type="submit" class="button">Sign Up</button>
                  </form>
			  </div>
		  </div>
