mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import settings
from django.conf.urls.static import static
from user import views as user_views

urlpatterns = [
    url('admin/', admin.site.urls, name='admin'),
    url('', include('homepage.urls')),
    url('product/', include('product.urls')),
    url('shop/', include('shop.urls')),
    url('user/', include('user.urls')),
    url('order/', include('order.urls')),
    url('basket/', include('user_basket.urls')),

    path('login/', user_views.Login, name='login'),
    path('logout/', user_views.LogOut, name='logout'),
    path('register/', user_views.UserSignUp, name='register'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


























order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns = [
    path('list/', views.OrderListView, name='list'),
    path('orderNO/Detail/', views.OrderDetailView, name='detail'),
    path('process-order/', views.BasketCheckOutProcess, name='process-order'),
    path('process/<product_id>/<shop_id>/', views.OrderProcessing, name='process'),
    path('order-detail/', views.OrderDetailView, name='order-detail'),
    path('place-order/', views.CheckoutBasketView, name='place-order'),
    path('checkout/<product_id>/<shop_id>/', views.CheckOutView, name='checkout')
]

product/urls.py
from django.urls import path
from django.conf.urls import url
from product import views

app_name = 'product'
urlpatterns = [
    # /products/
    path('', views.product_list, name='product-list'),

    # /product/<pk>/ # to be done later
    path('<pk>/', views.productView, name='productView'),
]

shop/urls.py
from django.urls import path
from . import views


app_name = 'Shop'
urlpatterns = [

    path('', views.ShopListView, name='shop-list'),

    path('sd/<pk>/', views.ShopDetailView, name='shop-detail'),

    path('sc/<pk>/context/', views.ShopDetailContextView, name='shop-context'),

    path('sr/<pk>/add_review/', views.ShopAddReview, name="add-review"),

    path('AddNewShop/', views.AddNewShop.as_view(), name="add-shop"),

    # path('something/', views.AddNewShop.as_view(), name="something")
]


user_basket/urls.py
from django.urls import path
from user_basket import views as basket_views

app_name = 'basket'
urlpatterns = [
    path('', basket_views.ListView, name='list'),
    path('add-item/<product_id>/<shop_id>/', basket_views.AddToBasket, name='add-item'),
    path('rm-item/<basket_product_id>/', basket_views.RemoveFromBasket, name='remove-item'),
    path('update-item/<int:basket_product_id>/', basket_views.UpdateQuantity, name='update'),
]

shop/models.py
from django.db import models
from django.contrib.auth.models import User
from product.models import product_data
from .model_options import states
from django.urls import reverse


class Shop(models.Model):
    title = models.CharField(max_length=50)

    # Communication Fields
    # phone = models.IntegerField()
    # email = models.EmailField()

    # Address Fields
    address_line_1 = models.CharField(max_length=200)   # Street name
    address_line_2 = models.CharField(max_length=100, null=True)   # City name
    address_State = models.CharField(max_length=20, choices=states)
    location = models.CharField(max_length=100)     # GPS location

    # About Shop
    about = models.CharField(max_length=500)
    rating = models.DecimalField(default=0, max_digits=3, decimal_places=1)
    Shop_icon = models.ImageField(verbose_name='Shop Photo 1')
    Shop_icon_2 = models.ImageField(verbose_name='Shop Photo 2', null=True)
    number_of_reviews = models.IntegerField(default=0)

    def add_review(self, new_rating, comment):

        shop = self
        new_rating_obj = review(shop=shop, rating=new_rating, comment=comment)
        new_rating_obj.save()

        shop.rating = (shop.number_of_reviews * float(shop.rating) + new_rating) / (shop.number_of_reviews + 1)
        shop.number_of_reviews += 1
        shop.save()

    def get_absolute_url(self):
        return reverse('Shop: shop-list')

    def __str__(self):
        return self.title


class product(models.Model):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    shop_product = models.ForeignKey(product_data, on_delete=models.CASCADE)
    available_quantity = models.IntegerField()

    def __str__(self):
        return self.shop_product.name


class review(models.Model):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    # review can be added in only if user is logged in, and after shopping from the Shop.
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.DecimalField(default=0, max_digits=3, decimal_places=1)      # max_value = 5
    comment = models.CharField(max_length=300, null=True)

    def __str__(self):
        return str(self.rating) + "  -  " + str(self.comment)[:10]

user_basket/models.py
from django.contrib.auth.models import User
from django.db import models
from product.models import product_data
from shop.models import Shop
from django.utils import timezone


class BasketManager(models.Manager):

    def all_products(self):
        return 'anything'


class basket(models.Model):
    class Meta:
        verbose_name = 'User Basket'
        db_table = 'User_Basket'

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        if self.user.first_name:
            return self.user.first_name + "'s Basket"
        else:
            return self.user.username + "'s Basket"

    @property
    def total_amount(self):
        return sum([(product_set.basket_product.price * product_set.quantity)
                    for product_set in self.basket_product_set.all()])


class basket_product(models.Model):
    basket_obj = models.ForeignKey(basket, on_delete=models.CASCADE)
    basket_product_shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    date_added = models.DateTimeField(default=timezone.now)
    basket_product = models.ForeignKey(product_data, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return str(self.quantity) + ' : ' + str(self.basket_product.name)

user_basket/views.py
from django.shortcuts import render, redirect, HttpResponse
from product import models as product_models
from shop import models as shop_models
from user_basket import models as basket_models


def ListView(request):
    """
    ListView function Show the item currently in Basket,
    :param request:
    :return: List of Items in User's Basket.
    : Modifications Required:
            1.
    """

    user = request.user
    if user.is_authenticated:
        try:
            basket_obj = basket_models.basket.objects.get(user=user)
        except basket_models.basket.DoesNotExist:
            basket_obj = basket_models.basket.objects.create(user=user)
            basket_obj.save()

        all_product_sets = basket_obj.basket_product_set.all().order_by('-date_added')

        return render(request, 'user_basket/basket-page.html', {
            'all_product_sets': all_product_sets,
            'basket_obj': basket_obj,
        })
    else:
        return render(request, 'user_basket/basket-page.html')


def AddToBasket(request, product_id, shop_id):
    """
    Function will be called to Add the item to the cart,
        A new instance for user_basket.models.basket_product.

    :param request:
    :param product_id:
    :param shop_id:
    :return: Doesn't Return anything, Just do the work.

    :: Modifications Required:
            1. all the parameter need to be removed and using form will be better.
            2. Handling error 'AddToBasket returned None'
            3. if product already in the basket
                increase the quantity if there is availability
                else Show the message "Not available."
    """
    user = request.user
    product = product_models.product_data.objects.get(pk=product_id)
    shop = shop_models.Shop.objects.get(pk=shop_id)
    if user.is_authenticated:
        basket_obj = basket_models.basket.objects.get(user=user)
        # Checking if product is already in the basket
        try:
            product_set = basket_obj.basket_product_set.get(basket_product=product)
            return HttpResponse('Product Already in Basket')
        except basket_models.basket_product.DoesNotExist:

            product_set = basket_obj.basket_product_set.create(basket_product=product, basket_product_shop=shop)
            product_set.save()
            return HttpResponse('Successfully Added.')
    else:
        # set to the cookie
        pass
        return HttpResponse('Successfully Added.')


def RemoveFromBasket(request, basket_product_id):
    user = request.user
    basket_obj = basket_models.basket.objects.get(user=user)
    try:
        basket_product = basket_obj.basket_product_set.get(pk=basket_product_id)
        basket_product.delete()

        # Redirect to the same page, currently redirecting to  basket
        return redirect('basket:list')

    except:
        return HttpResponse('Invalid Request!')


def UpdateQuantity(request, basket_product_id):
    user = request.user

    basket_obj = basket_models.basket.objects.get(user=user)
    try:
        basket_product = basket_obj.basket_product_set.get(pk=basket_product_id)

        # quantity = basket_product.quantity
        increase_by = request.GET['increase_by']
        if increase_by == '+1':
            print('increase_by is: ', increase_by)
            basket_product.quantity += 1
            basket_product.save()
            return redirect('basket:list')

        elif increase_by == '-1':
            if basket_product.quantity > 1:
                basket_product.quantity -= 1
                basket_product.save()
                return redirect('basket:list')

            elif basket_product.quantity == 1:
                """basket_product will be deleted!"""
                basket_product.delete()
                return redirect('basket:list')

            else:
                """Quantity cannot be made negative!"""
                return redirect('basket:list')

        elif increase_by == 'remove':
            basket_product.delete()
            return redirect('basket:list')

        else:
            """increase_by can only be 1, -1 or remove"""
            return redirect('basket:list')
    except Exception as e:
        """basket_product_set does not exist or doesn't belong to current user!"""
        return HttpResponse('Invalid Request!')

user_basket/templates/user_basket/basket-page.html
{% extends 'homepage/base.html' %}

{% block body %}

    {#    show below container only if there is any item in basket#}

    {% if basket_obj and all_product_sets %}
        <div class="container product-list">

            <div class="row justify-content-lg-start">
                <div class="col-sm-2"></div>
                <div class="col-sm-4"><strong>Basket Value: </strong>&#8377;{{ basket_obj.total_amount }}</div>
                <div class="col-sm-4"></div>
                <div class="col-sm-2">
                    <a href="{% url 'order:process-order' %}">
                        <button class="btn btn-outline-primary btn-group-lg">Checkout Basket</button>
                    </a>
                </div>
            </div>
            {% for product_set in all_product_sets %}

                <div class="row product-detail">
                    <div class="col-md-3">
                        <img src="{{ product_set.basket_product.image_link.url }}" alt="product-photo" height="80px">
                    </div>
                    <div class="col-md-6">
                        <strong>
                            <span>
                                <a href="{% url 'product:productView' product_set.basket_product.pk %}">
                                    {{ product_set.basket_product.name }}
                                </a>
                            </span>
                        </strong>
                        <br>
                        <strong>
                            <small>Sold By:
                                <a href="{% url 'Shop:shop-detail' product_set.basket_product_shop.pk %}">
                                    {{ product_set.basket_product_shop.title }}
                                </a>
                            </small>
                        </strong><br>

                        <form action="{% url 'basket:update' product_set.pk %}" method="get"
                              style="display: inline-block;">
                            {% csrf_token %}
                            <input type="hidden" value="-1" name="increase_by">
                            <button type="submit" class="btn btn-outline-secondary btn-sm">-</button>
                        </form>

                        <span style="display: inline-block;">{{ product_set.quantity }}</span>

                        <form action="{% url 'basket:update' product_set.pk %}" method="get"
                              style="display: inline-block;">
                            {% csrf_token %}
                            <input type="hidden" value="+1" name="increase_by">
                            <button type="submit" class="btn btn-outline-secondary btn-sm">+</button>
                        </form>
                    </div>
                    <div class="col-md-3" style="margin-top: 20px;">
                        Rs.{{ product_set.basket_product.price }} x {{ product_set.quantity }} <br><br>
                        <form action="{% url 'basket:update' product_set.pk %}" method="get">
                            {% csrf_token %}
                            <input type="hidden" value="remove" name="increase_by">
                            <button class="btn btn-outline-secondary btn-sm">Remove</button>
                        </form>
                    </div>
                </div>

            {% endfor %}

        </div>
    {% else %}
        <div class="container" style="min-height: 80vh;">
            <div class="row">
                <div class="col-sm-12"
                     style="background-color: #c8c8c8; padding: 10px; margin: 10px; text-align: center; border-radius: 5px;">
                    <strong>Your Basket is empty.<br>Add items and place your order.</strong>
                </div>
            </div>
        </div>
    {% endif %}

    <style>
        .product-detail {
            background-color: #c8c8c8;
            border: solid 1px #8c8c8c;
            border-radius: 10px;
            margin: 10px;
            padding: 10px;
        }

        .product-list {
            min-height: 400px;
        }
    </style>

{% endblock %}



