mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import settings
from django.conf.urls.static import static
from user import views as user_views

urlpatterns = [
    url('admin/', admin.site.urls, name='admin'),
    url('', include('homepage.urls')),
    url('product/', include('product.urls')),
    url('shop/', include('shop.urls')),
    url('user/', include('user.urls')),
    url('order/', include('order.urls')),
    url('basket/', include('user_basket.urls')),

    path('login/', user_views.Login, name='login'),
    path('logout/', user_views.LogOut, name='logout'),
    path('register/', user_views.UserSignUp, name='register'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


























order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns = [
    path('list/', views.OrderListView, name='list'),
    path('orderNO/Detail/', views.OrderDetailView, name='detail'),
    path('process-order/', views.BasketCheckOutProcess, name='process-order'),
    path('process/<product_id>/<shop_id>/', views.OrderProcessing, name='process'),
    path('order-detail/', views.OrderDetailView, name='order-detail'),
    path('place-order/', views.CheckoutBasketView, name='place-order'),
    path('checkout/<product_id>/<shop_id>/', views.CheckOutView, name='checkout')
]

product/urls.py
from django.urls import path
from django.conf.urls import url
from product import views

app_name = 'product'
urlpatterns = [
    # /products/
    path('', views.product_list, name='product-list'),

    # /product/<pk>/ # to be done later
    path('<pk>/', views.productView, name='productView'),
]

shop/urls.py
from django.urls import path
from . import views


app_name = 'Shop'
urlpatterns = [

    path('', views.ShopListView, name='shop-list'),

    path('sd/<pk>/', views.ShopDetailView, name='shop-detail'),

    path('sc/<pk>/context/', views.ShopDetailContextView, name='shop-context'),

    path('sr/<pk>/add_review/', views.ShopAddReview, name="add-review"),

    path('AddNewShop/', views.AddNewShop.as_view(), name="add-shop"),

    # path('something/', views.AddNewShop.as_view(), name="something")
]


user_basket/urls.py
from django.urls import path
from user_basket import views as basket_views

app_name = 'basket'
urlpatterns = [
    path('', basket_views.ListView, name='list'),
    path('add-item/<product_id>/<shop_id>/', basket_views.AddToBasket, name='add-item'),
    path('rm-item/<basket_product_id>/', basket_views.RemoveFromBasket, name='remove-item'),
    path('update-item/<int:basket_product_id>/', basket_views.UpdateQuantity, name='update'),
]

product/models.py
from django.db import models
from .model_options import category_options, attributes
import os

class product_data(models.Model):
    class Meta:
        verbose_name = "Product"
        db_table = "Products"

    name = models.CharField(max_length=100)     # product name given by the company
    category = models.CharField(max_length=20, choices=category_options)   # A json dict data # Nested
    image_link = models.ImageField(max_length=200)
    type = models.CharField(max_length=30)                          # Common name of the product.
    Brand = models.CharField(max_length=30)
    product_info = models.CharField(max_length=100)
    rating = models.DecimalField(max_digits=4, decimal_places=2)    # an expression for rating
    price = models.DecimalField(max_digits=9, decimal_places=2)

    @property
    def large_image(self):
        return self.image_link.url.replace('/media/', '/media/large/')

    def __str__(self):
        return self.name


class product_attributes(models.Model):

    product = models.ForeignKey(product_data, on_delete=models.CASCADE)
    attr = models.CharField(max_length=20, choices=attributes)
    value = models.CharField(max_length=200)

    def __repr__(self):
        return self.attr













# ================== ForeignKeys Data ========================

    # -----------------  Client Side(Data Entry Operator) ---------------------------
    #

    # ----------------- User side ----------------------------
    # numbers_of_this_item_in_basket = models.ForeignKey(default=0)
    # shops_with_availability = models.nearby_shops.filter(product_id=current_product_id)

    # ------------------ Seller Side ---------------------------

product/views.py
from django.shortcuts import render
from product.models import product_data


def product_list(request):
    products = product_data.objects.all()[:50]
    return render(request, 'product/product_list.html',
                  {'products': products})


def productView(request, pk):
    product = product_data.objects.get(pk=pk)
    return render(request, 'product/product-detail.html',
                  {'product': product})

product/templates/product/product-detail.html
{% extends 'homepage/base.html' %}
{% load static %}

{% block body %}
    <link rel="stylesheet" href="{% static 'product/CSS/Style4Product3.css' %}">
    <!-- code for laptop -->
    <div class="CodingOfProductPage4Laptop" >
        <div class="LeftSideProductPage">
            <div style="display: flex;">
                <div class="ProductImg" >
                    <img src="{{ product.large_image }}" style="max-width:95%;max-height:400px;margin:2% ">
                <a href="#" style="color:black;text-align:center;"><h6>Rate and Report</h6></a>
                </div>
                <div class="PINCheck">
                    <div class="Heading4Product">
                        <h2 style="text-align: left;padding:2%;">{{ product.name }}</h2>
                        <h3 style="text-align: left;padding:3%;padding-top: 0;">
                        By<a href="#" style="padding-left: 2%">nearby shop{{ nearby_shop }}</a>
                        </h3>
                    </div>
                    <div class="checkout4product">
                        <h4 style="text-align: left;padding:4%;padding-bottom:0">Features :-</h4>
                        <ul style="border-bottom: 1px solid black;">
                            <li>Type of product : {{ product.type }}</li>
                            <li>Weight :{{ product.a }}</li>
                            <li>Flavour :</li>
                            <li>Brand: {{ product.Brand }}</li><br>
                            {% for key, value in product.product_attributes_set.all %}
                            <li>{{ Key }}: {{ value }}</li>
                            {% endfor %}
                            <a href="#More2"><b>More details</b></a>
                        </ul>
                        <h4 style="padding:3%;padding-bottom: 0;">Check availability and COD on your location</h4>
                        <form class="form-inline" style="margin: 3%;margin-top: 0;">
                            <input class="form-control mr-sm-2" type="search" placeholder="Enter your Pincode" aria-label="Search" style="background-color:mintcream">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Check</button>
                        </form>
                    </div>
                </div>
            </div>
        <div id="More2" class="More">
        <h2>Product Specifications</h2>
        <h6 style="border-bottom:1px dotted black;height:50px;">Weight:</h6>
        <h6 style="border-bottom:1px dotted black;height:50px;">Weight:</h6>
        <h6 style="border-bottom:1px dotted black;height:50px;">Weight:</h6>
        <h6 style="border-bottom:1px dotted black;height:50px;">Weight:</h6>
        <h6 style="border-bottom:1px dotted black;height:50px;">Weight:</h6>
        <h6 style="border-bottom:1px dotted black;height:50px;">Weight:</h6>
        <h6 style="border-bottom:1px dotted black;height:50px;">Weight:</h6>
        <h6 style="border-bottom:1px dotted black;height:50px;">Weight:</h6>
        <h6 style="border-bottom:1px dotted black;height:50px;">Weight:</h6>
        </div>
        </div>
        <div class="RightSideProductPage">
        <div class="BuyProduct ">
        <div style="border-bottom:1px solid black;">
        <h5><del>Price Rs 1400</del></h5>
        <h1>Rs 1200 </h1><a href="#" style="padding-left:20%;">(Know more)</a>
        <h5>Price per piece Rs 120</h5>
        <h5>(15% OFF) You saved Rs 200</h5>
        </div>
        <div style="border-bottom:1px solid black;">
        <h3 style="margin-top:10px; margin-bottom:10px;">Buy in bulk & save more</h3>
        </div>
        <div>
        <table class="table">
        <thead style="background-color:#f1f1f1;">
        <tr>
        <th>Select</th>
        <th>Quantity</th>
        <th>Discount</th>
        <th>/ Price</th>
        </tr>
        </thead>
        <tbody>
        <tr>
        <td><input type="radio" name="PriceFormate" value="PickUrPrice"></td>
        <td>1-4</td>
        <td>4%</td>
        <td>144/-</td>
        </tr>
        <tr>
        <td><input type="radio" name="PriceFormate" value="PickUrPrice"></td>
        <td>5-8</td>
        <td>10%</td>
        <td>135/-</td>
        </tr>
        <tr>
        <td><input type="radio" name="PriceFormate" value="PickUrPrice"></td>
        <td>9+</td>
        <td>15%</td>
        <td>120/-</td>
        </tr>
        </tbody>
        </table>
        <button type="button" class="btn btn-primary" style="width:100%;"><h4>Buy Now</h4></button>
        <button type="button" class="btn " style="width:100%;background-color:lightgreen;margin-top:10px;color:white;"><h5>Add to cart</h5></button>
        </div>
        </div>
        </div>
    </div>

    <!-- Code for Mobile -->
    <div class="CodingOfProductPage4Mobile">
        <div class="FirstSectionOfProductPage4Mobile">
            <h5 style="padding-left: 2%">{{ product.name }} by <a href="#">nearby shop{{ nearby_shop }}</a></h5>
            <img class="ProductImg4Mobile" src="{{ product.large_image }}">
            <h6 class="RateAndReview4MobileInProductPage"><a style="color: black;" href="#">Rate and review</a></h6>
            <div class="ShortFeatures4MobileOfAProduct">
                <h4>Features</h4>
                    <li>Type of product : {{ product.type }}</li>
                    <li>Weight :</li>
                    <li>Flavour :</li>
                    <li>Brand: {{ product.Brand }}</li>
                <a href="#More3">More details</a>
            </div>
            <h6 style="padding:2%">Check availability and COD on your location</h6>
            <form class="form-inline" style="padding:2%;padding-top:0;">
                <input class="form-control mr-sm-2" type="search" placeholder="Enter your Pincode" aria-label="Search">
            </form>
            <div class="PriceTag4ProductPage4Mobile ">
                <div style="border-bottom:1px solid black;">
                    <h5 style="padding-left:10px;"><del>MRP Rs 1400</del>
                    <b>Rs 1200 </b><a href="#" style="padding-left:10%;">(Know more)</a></h5>
                    <h6 style="padding-left:10px;">Price per piece Rs 120
                    (15% OFF) <br><b>You saved Rs 200</b></h6>
                </div>
                <div style="border-bottom:1px solid black;">
                    <h5 style="margin-top:10px; margin-bottom:10px;padding-left:10px">Buy in bulk & save more</h5>
                </div>
            <div>
            <table class="table">
                <thead style="background-color:#f1f1f1;">
                    <tr>
                        <th>Select</th>
                        <th>Quantity</th>
                        <th>Discount</th>
                        <th>/ Price</th>
                    </tr>
                </thead>
            <tbody>
            <tr>
                <td><input type="radio" name="PriceFormate" value="PickUrPrice"></td>
                <td>1-4</td>
                <td>4%</td>
                <td>144/-</td>
            </tr>
            <tr>
                <td><input type="radio" name="PriceFormate" value="PickUrPrice"></td>
                <td>5-8</td>
                <td>10%</td>
                <td>135/-</td>
            </tr>
            <tr>
                <td><input type="radio" name="PriceFormate" value="PickUrPrice"></td>
                <td>9+</td>
                <td>15%</td>
                <td>120/-</td>
            </tr>
            </tbody>
            </table>
            <button type="button" class="btn btn-primary" style="width:45%;margin-left:3%;margin-bottom:2%">Buy Now</button>
            <button type="button" class="btn " style="width:45%;margin-bottom:2%;background-color:red;margin-left:10px;color:white;">Add to cart</button>

            </div>
            </div>
            <div id="More3" class="SecondSectionOfProductPage4Mobile">
            <h2>Product Specifications</h2>
            <h6 class="H6SecondSectionOfProductPage4Mobile" >Weight:</h6>
            <h6 class="H6SecondSectionOfProductPage4Mobile" >Weight:</h6>
            <h6 class="H6SecondSectionOfProductPage4Mobile" >Weight:</h6>
            <h6 class="H6SecondSectionOfProductPage4Mobile" >Weight:</h6>
            <h6 class="H6SecondSectionOfProductPage4Mobile" >Weight:</h6>
            <h6 class="H6SecondSectionOfProductPage4Mobile" >Weight:</h6>
            <h6 class="H6SecondSectionOfProductPage4Mobile" >Weight:</h6>
            <h6 class="H6SecondSectionOfProductPage4Mobile" >Weight:</h6>
            <h6 class="H6SecondSectionOfProductPage4Mobile" >Weight:</h6>
            </div>
        </div>
    </div>
{% endblock %}

product/templates/product/product_list.html
{% extends 'homepage/base.html' %}
{% load static %}
{% block body %}
    <div class="container" style="margin-top: 10px; align-items: center;">
        {% if error_message %}
            <div class="row justify-content-around">
                <div class="col-sm-8"
                     style="background-color: #c8c8c8; border-radius: 5px; padding: 5px; margin: 5px; text-align: center; min-height: 40px;">
                    <span>
                        <strong>{{ error_message }}</strong>
                    </span>
                </div>
            </div>
        {% endif %}

        {% for product in products %}

            <div class="product"
                 style=" width:200px; height: 320px; border: 0.1px solid grey; padding: 2px;background-color: #fff; float: left; margin: 5px;">
                <a href="{% url 'product:productView' product.pk %}" style=" text-decoration: none;">
                    <h6 style="text-align: center;">
                        {{ product.name }}
                        <img src="{{ product.image_link.url }}" alt="thumbnail" width="150px"><br>
                    </h6>
                </a>
                <b class="PriceDetailsInTemplate">
                    <small>
                        <del>MRP Rs. {{ product.price }}</del>
                    </small>
                    <br>Price Rs. {{ product.price }}
                </b><br>


                {% if product.pk > 200 %}
                    <a href="{% url 'order:process' product.pk 2 %}">
                        <img src="{% static 'homepage/Pics/checkout.png' %}" class="BuyNowButtonStyle" alt="Buy">
                    </a>
                    <a href="{% url 'basket:add-item' product.pk 2 %}"><i
                            class="fas fa-cart-plus AddToCartButtonStyle"></i></a>

                {% else %}

                    <a href="{% url 'order:process' product.pk 3 %}">
                        <img src="{% static 'homepage/Pics/checkout.png' %}" class="BuyNowButtonStyle" alt="Buy">
                    </a>
                    <a href="{% url 'basket:add-item' product.pk 3 %}"><i
                            class="fas fa-cart-plus AddToCartButtonStyle"></i></a>
                {% endif %}

            </div>&nbsp;
        {% endfor %}
    </div>
    <!-- Go to page n -->
{% endblock %}




