mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import settings
from django.conf.urls.static import static
from user import views as user_views

urlpatterns = [
    url('admin/', admin.site.urls, name='admin'),
    url('', include('homepage.urls')),
    url('product/', include('product.urls')),
    url('shop/', include('shop.urls')),
    url('user/', include('user.urls')),
    url('order/', include('order.urls')),
    url('basket/', include('user_basket.urls')),

    path('login/', user_views.Login, name='login'),
    path('logout/', user_views.LogOut, name='logout'),
    path('register/', user_views.UserSignUp, name='register'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


























order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns = [
    path('list/', views.OrderListView, name='list'),
    path('orderNO/Detail/', views.OrderDetailView, name='detail'),
    path('process-order/', views.BasketCheckOutProcess, name='process-order'),
    path('process/<product_id>/<shop_id>/', views.OrderProcessing, name='process'),
    path('order-detail/', views.OrderDetailView, name='order-detail'),
    path('place-order/', views.CheckoutBasketView, name='place-order'),
    path('checkout/<product_id>/<shop_id>/', views.CheckOutView, name='checkout')
]

product/urls.py
from django.urls import path
from django.conf.urls import url
from product import views

app_name = 'product'
urlpatterns = [
    # /products/
    path('', views.product_list, name='product-list'),

    # /product/<pk>/ # to be done later
    path('<pk>/', views.productView, name='productView'),
]

shop/urls.py
from django.urls import path
from . import views


app_name = 'Shop'
urlpatterns = [

    path('', views.ShopListView, name='shop-list'),

    path('sd/<pk>/', views.ShopDetailView, name='shop-detail'),

    path('sc/<pk>/context/', views.ShopDetailContextView, name='shop-context'),

    path('sr/<pk>/add_review/', views.ShopAddReview, name="add-review"),

    path('AddNewShop/', views.AddNewShop.as_view(), name="add-shop"),

    # path('something/', views.AddNewShop.as_view(), name="something")
]


Trash/order/models.py
from django.db import models

# Create your models here.

order/models.py
from django.db import models
from django.contrib.auth.models import User
from product.models import product_data
from shop.models import Shop
from django.utils import timezone
from order.model_options import numbers
from user import models as user_models


class user_order(models.Model):
    class Meta:
        verbose_name = 'User Order'
        db_table = 'User Order'

    # order_number = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered_from_shop = models.ForeignKey(Shop, verbose_name='Sold by', on_delete=models.PROTECT)

    # shipping_address = models.ForeignKey(user_models.user_address,
    #                                      verbose_name='shipping address',
    #                                      on_delete=models.PROTECT)

    date_ordered = models.DateTimeField(default=timezone.now)
    total_amount = models.DecimalField(null=True, decimal_places=2, max_digits=9)

    def __str__(self):
        return self.user.username + '\'s Order from ' + self.ordered_from_shop.title

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        x = sum([
            (product.ordered_quantity * product.ordered_product.price)
            for product in self.user_order_products_set.all()
        ])

        self.total_amount = x
        super().save()


# product will have to be grouped in basket.
# !!! Below class should have only one
# instance for one user_order instance
class user_order_products(models.Model):
    class Meta:
        verbose_name = 'Ordered Product'
        verbose_name_plural = 'Ordered Products'
        db_table = 'Ordered Products'

    for_order = models.ForeignKey(user_order, on_delete=models.CASCADE)
    ordered_product = models.ForeignKey(product_data, on_delete=models.PROTECT)

    # ordered quantity will be shown in user order history
    # and quantity_available will decrease from the shop
    ordered_quantity = models.IntegerField(default=1, choices=numbers)
    product_price = models.DecimalField(null=True, max_digits=9, decimal_places=2)

    # Check if promotions are available and applied

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.product_price = self.ordered_product.price * self.ordered_quantity
        super().save()

    def __str__(self):
        return self.for_order.user.username + '\'s Products ordered from ' + self.for_order.ordered_from_shop.title

# 1. Need to find a dictionary like model for the user_order, as this is not the proper way.
#       >> if not model manager can be used to return dictionary like object
#       >> another option is to create a Model Field

# 2. Here user_order can be used as abstract class for user_order_products
#       >> will be better than now. (27.01.2019)
#       >>
#       >>

# 3.

shop/models.py
from django.db import models
from django.contrib.auth.models import User
from product.models import product_data
from .model_options import states
from django.urls import reverse


class Shop(models.Model):
    title = models.CharField(max_length=50)

    # Communication Fields
    # phone = models.IntegerField()
    # email = models.EmailField()

    # Address Fields
    address_line_1 = models.CharField(max_length=200)   # Street name
    address_line_2 = models.CharField(max_length=100, null=True)   # City name
    address_State = models.CharField(max_length=20, choices=states)
    location = models.CharField(max_length=100)     # GPS location

    # About Shop
    about = models.CharField(max_length=500)
    rating = models.DecimalField(default=0, max_digits=3, decimal_places=1)
    Shop_icon = models.ImageField(verbose_name='Shop Photo 1')
    Shop_icon_2 = models.ImageField(verbose_name='Shop Photo 2', null=True)
    number_of_reviews = models.IntegerField(default=0)

    def add_review(self, new_rating, comment):

        shop = self
        new_rating_obj = review(shop=shop, rating=new_rating, comment=comment)
        new_rating_obj.save()

        shop.rating = (shop.number_of_reviews * float(shop.rating) + new_rating) / (shop.number_of_reviews + 1)
        shop.number_of_reviews += 1
        shop.save()

    def get_absolute_url(self):
        return reverse('Shop: shop-list')

    def __str__(self):
        return self.title


class product(models.Model):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    shop_product = models.ForeignKey(product_data, on_delete=models.CASCADE)
    available_quantity = models.IntegerField()

    def __str__(self):
        return self.shop_product.name


class review(models.Model):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    # review can be added in only if user is logged in, and after shopping from the Shop.
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.DecimalField(default=0, max_digits=3, decimal_places=1)      # max_value = 5
    comment = models.CharField(max_length=300, null=True)

    def __str__(self):
        return str(self.rating) + "  -  " + str(self.comment)[:10]

Trash/order/views.py
from django.shortcuts import render

# Create your views here.

order/views.py
from django.shortcuts import render, HttpResponse, reverse
from order import models as user_models
from product import models as product_models
from django.contrib.auth.decorators import login_required
from user_basket.models import basket
from shop import models as shop_models


@login_required
def OrderListView(request):
    user = request.user
    all_orders = user_models.user_order.objects.filter(user=user).order_by('-date_ordered')

    return render(request, 'order/order_list.html',
                  {'all_order': all_orders})


@login_required
def BasketCheckOutProcess(request):
    user = request.user

    basket_obj = basket.objects.get(user=user)
    all_basket_product_sets = basket_obj.basket_product_set.all()

    return render(request, 'order/order_processing.html', {
        'all_basket_product_sets': all_basket_product_sets,
        'basket_obj': basket_obj,
    })


@login_required
def OrderProcessing(request, product_id, shop_id):
    """
    OrderProcessing takes the user to a page to confirm the items and make payment.
    :param request:
    :param product_id:
    :param shop_id:
    :return:
    """
    user = request.user
    product = product_models.product_data.objects.get(pk=product_id)
    shop = shop_models.Shop.objects.get(pk=shop_id)

    # try:
    #     # if quantity
    #         pass
    # except:
    #   quantity = 1

    quantity = 1

    return render(request, 'order/order_processing.html', {
        'SingleCheckout': True,
        'shop': shop,
        'product': product,
        'quantity': quantity,
        'total_amount': product.price * quantity,
    })


@login_required
def OrderDetailView(request):
    # get order id
    # get products and quantity
    # pass product list in context

    products = [product_models.product_data.objects.get(name='Maggie'),
                product_models.product_data.objects.get(name='Choco Pie - Premium Quality')]

    return render(request, 'order/order-detail.html',
                  {'products': products})


@login_required
def CheckoutBasketView(request):
    """
    CheckoutBasketView checkout all the product in basket.
    It groups the product according to shop.
    There is a different order for every shop.
    Constraint should be applied for max number of shop per checkout.

    :param request:
    :return:


    ** Exception handling is not applied**

     >> shop_and_product is json like object
    shop_and_product = { shop1: {
                                    product1 : quantity
                                    product2 : quantity
                                    ....
                                    }

                         shop2: {
                                    product1 : quantity
                                    product2 : quantity
                                    ....
                                    }
                        ......
    """
    user = request.user
    basket_obj = basket.objects.get(user=user)

    all_basket_product_sets = basket_obj.basket_product_set.all()
    shop_and_products = {}

    for product_set in all_basket_product_sets:
        shop = product_set.basket_product_shop

        if shop not in shop_and_products:
            shop_and_products[shop] = {}

        product = product_set.basket_product
        quantity = product_set.quantity
        shop_and_products[shop][product] = quantity

    # placing orders one by one
    # one order from one shop
    # two different shop can't have same order
    for shop, products_dict in shop_and_products.items():
        order = user_models.user_order.objects.create(user=user, ordered_from_shop=shop)

        for product in products_dict:
            user_order_product_set = user_models.user_order_products.objects.create(
                for_order=order, ordered_product=product, ordered_quantity=products_dict[product]
            )
            user_order_product_set.save()

        order.save()
    # After the order has been placed successfully
    # Delete the products from basket
    # Missing -- Check if the order was successful or not before deleting.

    for product_set in all_basket_product_sets:
        product_set.delete()

    return render(request, 'order/order-successful.html')


@login_required
def CheckOutView(request, product_id, shop_id):
    """
    CheckOutView places the order for single product.



    :param request:
    :param product_id:
    :param shop_id:
    :return:
    """
    user = request.user
    product = product_models.product_data.objects.get(pk=product_id)
    shop = shop_models.Shop.objects.get(pk=shop_id)
    order = user_models.user_order.objects.create(user=user, ordered_from_shop=shop)

    user_order_product_set = user_models.user_order_products.objects.create(
        for_order=order, ordered_product=product, ordered_quantity=1
    )

    user_order_product_set.save()
    order.save()
    return render(request, 'order/order-successful.html')

order/templates/order/order-detail.html
{% extends 'homepage/base.html' %}
{% load static %}

{% block title %}Order Description{% endblock %}

{% block body %}
    <div class="container order-checkout">
        <div class="row payment_address">
            <div class="col-md-6 col-sm-12 address">
                <div>
                    <div class="address-details">
                        <span class="recipient-name"><strong>Deepak Kumar</strong></span><br>
                        <span class="address-line-1">Sai Mandir Patliputra</span><br>
                        <span class="address-line-2">Patliputra Colony</span><br>
                        <span class="city">Patna</span><br>
                        <span class="pin-code">800013</span>
                        <span class="State">Bihar</span>
                    </div>
{#                    <div class="address-details">#}
{#                        <span class="recipient-name"><strong>Deepak Kumar</strong></span><br>#}
{#                        <span class="address-line-1">Sai Mandir Patliputra</span><br>#}
{#                        <span class="address-line-2">Patliputra Colony</span><br>#}
{#                        <span class="city">Patna</span><br>#}
{#                        <span class="pin-code">800013</span>#}
{#                        <span class="State">Bihar</span>#}
{#                    </div>#}
                </div>
                <div class="payment">
                    <span>Rs.204.00 Paid Successfully using Card xxx1234</span>
                </div>

            </div>

            <div class="order-status">
                <span><strong>Delevered on:</strong> 13 Jan 2019</span><br><br>
                <small><strong>Reached the destination:</strong> 2:00 PM, 13 Jan 2019</small><br>
                <small><strong>Order Proccessed and sent:</strong> 01:30 PM, 13 Jan 2019</small><br>
                <small><strong>Order Placed:</strong> 12:30 AM, 13 Jan 2019</small><br>

            </div>
        </div>
    <div class="row order_summary" style="background-color: #c8c8c8;">
{#                    <div class="row" style="padding-top: 5px; background-color: #fff;">#}
                <div class="col-sm-5" style="text-align: center;">
                    <span><strong>Sold By</strong></span><br>
                    <span><a href="#" style="text-decoration: None;">Shop name</a></span>
                </div>
                <div class="col-sm-5" style="text-align: center;">
                    <span><strong>Total amount: </strong></span><br>
                    <span style="color: #003eff;">Rs.204.00</span>
                </div>
    </div>
{% for product in products %}
        <div class="row product">
                <div class="row a-box-shipment">
                        <div class="col-sm-2" style="padding-top: 10px;">
                            <a href="{% url 'product:productView' product.pk %}" style="text-decoration: None;">
                            <img src="{{ product.image_link.url }}" alt="image" style=" height: 80px;"></a>
                        </div>
                        <div class="col-sm-6" style="padding-top: 10px;">
                                <span style="color: #1b1e21;">
                                    <strong>
                                        <a href="{% url 'product:productView' product.pk %}" style="text-decoration: None;">{{ product.name }}</a></strong>
                                </span><br>
                                <span>Qty: 10{{ product_quantity }}</span>
                        </div>
                        <div class="col-sm-4" style="text-align: center; padding-top: 10px;">
                            <span><strong>Price:</strong> Rs. {{ product.price }}x{{ product_quantity }}</span>
                        </div>
                </div>
        </div>
    {% endfor %}

    </div>


    <style>
        .order-checkout{

        }
        .payment_address{
            background-color: #fff;
            border: solid #c8c8c8 1px;
            border-radius: 10px;
        }
        .address{

        }
        .address-details{
            margin: 5px;
            padding: 5px;
            width: 30%;
            background-color: #fff;
            border: solid #c8c8c8 0.5px;
            border-radius: 5px;
            {#float: left;#}
            display: inline-block;
        }
        .order-status{
            margin: 5px;
            padding: 5px;
            width: 30%;
            border: solid #c8c8c8 1px ;
        }
        .payment{
            margin: 5px;
            padding: 5px;
            width: 200px;
            height: 100px;
            background-color: #fff;
            border: solid #c8c8c8 0.5px;
            border-radius: 5px;
        }
        .a-box-shipment{
            margin: 5px;
            padding: 5px;
            width: 100%;
            background-color: #fff;
            height: 120px;
            border-radius: 5px;
        }
    </style>

{% endblock %}

order/templates/order/order-successful.html
{% extends 'homepage/base.html' %}

{% block body %}

    <div class="container" style="min-height: 70vh;">
        <div class="row">
            <div class="col-sm-12" style="background-color: #c8c8c8; margin: 5px; padding: 5px; border-radius: 5px; text-align: center;">
                <h3><strong>Your order has been placed successfully.</strong></h3>
            </div>
        </div>
    </div>

{% endblock %}

order/templates/order/order_list.html
{% extends 'homepage/base.html' %}
{% load static %}
{% block title %}Order History{% endblock %}
{% block body %}
    <h5 style="text-align: center; color: #ff0000;">
        <strong>Order Number</strong> and <strong>Shipped to</strong> are currently not working..
    </h5>
    <div class="container-fluid all_orders" style="padding-top: 10px; margin-top: 40px;">
{#             for order in all_orders_list                  #}
        {% for order in all_order %}

        <div class="row justify-content-center" style="margin-bottom: 5px;">
{#            <div class="col-sm-2"></div>                   #}
            <div class="col-sm-8" style="background-color: lightgrey; border-radius: 5px;">
                <div class="a-row" style="border-bottom: solid lightgrey 0.5px">
                    <div class="container-fluid" >
                        <div class="row">

                            <div class="col-md-2">
                                <strong>Order Placed</strong><br>
                                <span>{{ order.date_ordered.date }}</span>
                            </div>
                            <div class="col-md-2">
                                <strong>Shipped to</strong><br>
                                <i class="fa fa-map-marker"></i> Patliputra
                            </div>
                            <div class="col-md-2">
                                <strong>Total Amount</strong>
                            <span>Rs. {{ order.total_amount }}</span>
                            </div>
                            <div class="col-md-4"></div>
                            <div class="col-md-2" style="text-align: right">
                                <strong>Order Number</strong>
                                <span>#456798765</span>
                            </div>

                        </div>
                    </div>
                </div>

            <!-- Status Bar -->
            <div class="row" style="padding-top: 5px; background-color: #fff;">
                <div class="col-sm-2">
                    <span><strong>Delevery status</strong></span><br>
                    <span>Delivered</span>
                </div>
                <div class="col-sm-5">
                    <span><strong>Bought From: </strong></span>
                    <span style="color: #003eff;"><a href="{% url 'Shop:shop-detail' order.ordered_from_shop.pk %}" style="text-decoration: None;">{{ order.ordered_from_shop.title }}</a></span>
                </div>
                <div class="col-sm-2">
                    <button class="btn btn-outline-info" style="height: 38px; width: 150px;"> Track</button>
                </div>
                <div class="col-sm-2" style="margin-left: 10px;">
                    <button class="btn btn-outline-info" style="height: 38px; width: 150px;">Contact Support</button>
                </div>
            </div>

            <!-- Shipments -->
                {% for shipment_set in order.user_order_products_set.all %}
                        <div class="row a-box-shipment" style="background-color: #fff; height: 120px; border-radius: 5px;">
                            <div class="col-sm-2" style="padding-top: 10px;">
                                <a href="{% url 'product:productView' shipment_set.ordered_product.pk %}" style="text-decoration: None;">
                                <img src="{{ shipment_set.ordered_product.image_link.url }}" alt="image"
                                     style=" height: 80px;"></a>
                            </div>

                            <div class="col-sm-6" style="padding-top: 10px;">
                                    <span style="color: #1b1e21;"><strong>
                                        <a href="{% url 'product:productView' shipment_set.ordered_product.id %}" style="text-decoration: None;">{{ shipment_set.ordered_product.name }}</a></strong></span><br>
                                    <span>Qty: {{ shipment_set.ordered_quantity }}</span>
                            </div>

                            <div class="col-sm-4" style="text-align: center; padding-top: 10px;">
                                <span><strong>Price:</strong> Rs.{{ shipment_set.product_price }}</span>
                            </div>
                        </div>

                    {% endfor %}
{##}
            </div>
        </div>

        {% endfor %}

    </div>
    <style>
    a{
        text-decoration: None;
    }
    </style>
{% endblock %}

order/templates/order/order_processing.html
{# this page will contain informations about the current order being placed #}
{# at this page user will be able to change the address, payment options,   #}
{# quantity of diffrent products, and apply coupons. after this page user  #}
{# will be redirected to payment gateway and after succesfull payment order #}
{# will be placed. #}


{% extends 'homepage/base.html' %}
{% load static %}
{% block title %}Check Out{% endblock %}
{% block body %}
    <div class="container order-checkout">
        <div class="row payment_address">
            <div class="col-md-6 col-sm-12 address">
                <div>
                    <div class="address-details">
                        <span class="recipient-name"><strong>Deepak Kumar</strong></span><br>
                        <span class="address-line-1">Sai Mandir Patliputra</span><br>
                        <span class="address-line-2">Patliputra Colony</span><br>
                        <span class="city">Patna</span><br>
                        <span class="pin-code">800013</span>
                        <span class="State">Bihar</span>
                    </div>

                    <div class="address-details">
                        <span class="recipient-name"><strong>Deepak Kumar</strong></span><br>
                        <span class="address-line-1">Sai Mandir Patliputra</span><br>
                        <span class="address-line-2">Patliputra Colony</span><br>
                        <span class="city">Patna</span><br>
                        <span class="pin-code">800013</span>
                        <span class="State">Bihar</span>
                    </div>
                </div>
                <div class="payment">
                </div>
            </div>
            <div class="col-sm-4 location-on-map">
                <img src="/media/map.jpg" alt="map" width="400px;" height="160;">
            </div>
        </div>
    {% if all_basket_product_sets %}
        <div class="row order_summary justify-content-between" style="background-color: #c8c8c8; margin: 5px; padding: 5px;">
            <div class="col-sm-5" style="padding: 10px;">
                <span><strong>Total amount: </strong></span>
                <span style="color: #003eff;">&#8377; {{ basket_obj.total_amount }}</span>
            </div>
            <div class="col-sm-5" style="text-align: right;">
                <a href="{% url 'order:place-order' %}">
                    <button class="btn btn-outline-primary">Place Order</button>
                </a>
            </div>
        </div>



    {% elif SingleCheckout %}
        <div class="row order_summary justify-content-between" style="background-color: #c8c8c8; margin: 5px; padding: 5px;">
            <div class="col-sm-5" style="padding: 10px;">
                <span><strong>Total amount: </strong></span>
                <span style="color: #003eff;">&#8377; {{ total_amount }}</span>
            </div>
            <div class="col-sm-5" style="text-align: right;">
                <a href="{% url 'order:checkout' product.pk shop.pk %}">
                    <button class="btn btn-outline-primary">Place Order</button>
                </a>
            </div>
        </div>
    {% endif %}
{#  for CheckOut From Basket                 #}
{% for product_set in all_basket_product_sets %}
        <div class="row product">
                <div class="row a-box-shipment">
                            <div class="col-sm-2" style="padding-top: 10px;">
                                <a href="{% url 'product:productView' product_set.basket_product.pk %}" style="text-decoration: None;">
                                <img src="{{ product_set.basket_product.image_link.url }}" alt="image" style=" height: 80px;"></a>
                            </div>

                            <div class="col-sm-6" style="padding-top: 10px;">
                                    <span style="color: #1b1e21;">
                                        <strong>
                                            <a href="{% url 'product:productView' product_set.basket_product.pk %}" style="text-decoration: None;">
                                                {{ product_set.basket_product.name }}
                                            </a>
                                        </strong>
                                    </span><br>
                                    <span>
                                        <strong>Sold By: </strong>

                    <span><a href="#" style="text-decoration: None;">{{ product_set.basket_product_shop.title }}</a></span>

                                    </span>
                            </div>
                            <div class="col-sm-4" style="text-align: left; padding-top: 10px;">
                                <span><strong>Qty: </strong>{{ product_set.quantity }}</span><br>
                                <span>
                                    <strong>Price:</strong>
                                    &#8377; {{ product_set.basket_product.price }} x {{ product_set.quantity }}
                                </span>
                            </div>
                </div>
        </div>
    {% endfor %}

    <!-- ############################ -->
    <!-- ############################ -->
    <!-- ############################ -->
    <!-- ############################ -->
    <!-- ############################ -->
    <!-- ############################ -->
    <!-- ############################ -->
    <!-- ############################ -->

    {# For single CheckOut #}
    {% if SingleCheckout %}
        <div class="row">
            <div class="col-sm-12">
                <div class="row product">
                <div class="row a-box-shipment">
                            <div class="col-sm-2" style="padding-top: 10px;">
                                <a href="{% url 'product:productView' product.pk %}" style="text-decoration: None;">
                                <img src="{{ product.image_link.url }}" alt="image" style=" height: 80px;"></a>
                            </div>

                            <div class="col-sm-6" style="padding-top: 10px;">
                                    <span style="color: #1b1e21;">
                                        <strong>
                                            <a href="{% url 'product:productView' product.pk %}" style="text-decoration: None;">
                                                {{ product.name }}
                                            </a>
                                        </strong>
                                    </span><br>
                                    <span>
                                        <strong>Sold By: </strong>

                    <span><a href="#" style="text-decoration: None;">{{ shop.title }}</a></span>

                                    </span>
                            </div>
                            <div class="col-sm-4" style="text-align: left; padding-top: 10px;">
                                <span><strong>Qty: </strong>{{ quantity }}</span><br>
                                <span>
                                    <strong>Price:</strong>
                                    &nbsp;&nbsp;&#8377; {{ product.price }} x {{ quantity }}
                                </span>
                            </div>
                </div>
        </div>
            </div>
        </div>
    {% endif %}
    </div>

    <style>
        .order-checkout{

        }
        .payment_address{
            background-color: #fff;
            border: solid #c8c8c8 1px;
            border-radius: 10px;
        }
        .address{

        }
        .address-details{
            margin: 5px;
            padding: 5px;
            width: 30%;
            background-color: #fff;
            border: solid #c8c8c8 0.5px;
            border-radius: 5px;
            {#float: left;#}
            display: inline-block;
        }
        .location-on-map{
            margin: 5px;
            padding: 5px;
        }
        .payment{
            margin: 5px;
            width: 200px;
            height: 100px;
            background-color: #fff;
            border: solid #c8c8c8 0.5px;
            border-radius: 5px;
        }
        .a-box-shipment{
            margin: 5px;
            padding: 5px;
            width: 100%;
            background-color: #fff;
            height: 120px;
            border-radius: 5px;
        }
    </style>
{% endblock %}
